### ISSUE TITLE
I2C slave example?

### ISSUE THREAD

**Issue by vanminh0910** [AlexanderMandera/arduino-wch32v003#10]
Thanks for great resource to support CH32V003 on Arduino. It makes life much easier for beginner like me to play with. Is there any slave i2c example? I plan to use this dead cheap mcu in some of my sensors and convert them all to i2c module. Thanks.

**Comment by AlexanderMandera** [comment]
You can use the i2c_slave example from ch32v003fun:
https://github.com/cnlohr/ch32v003fun/tree/master/examples%2Fi2c_slave

There is a header-file library that you can use. In the C file there is the usage of this library.

The example doesn't use Arduino, but maybe it can help you achieving your goal. In the future, this could be created as a library for easier use.

For other examples, you can always look in the examples folder of ch32v003fun, they should be compatible with the Arduino IDE too.
