### ISSUE TITLE
error no malloc and .L0 

### ISSUE THREAD

**Issue by micropythondevel** [AlexanderMandera/arduino-wch32v003#12]
riscv-none-elf-g++: warning: '-x c++' after last input file has no effect
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino: In function 'void editln()':
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:26:23: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   26 |         p=findstr(buf," ");
      |                       ^~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:27:24: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   27 |         if(findstr(buf," ")) {
      |                        ^~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino: In function 'void loop()':
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:183:23: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  183 |                 puts2("\n\rOk\n\r");
      |                       ^~~~~~~~~~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:196:48: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  196 |                                 if (!findstr(s,"\"")){
      |                                                ^~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:197:59: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  197 |                                         while(p=findstr(s,"<>"))
      |                                                           ^~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:199:59: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  199 |                                         while(p=findstr(s,"<="))
      |                                                           ^~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:201:59: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  201 |                                         while(p=findstr(s,">="))
      |                                                           ^~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:273:71: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  273 |                                               if(quoted&1 || !findstr(" \t",F))//what in the world does this line do?
      |                                                                       ^~~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:314:74: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  314 |                                                         (*(q=findstr(buf,"TH"))=0,
      |                                                                          ^~~~
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:357:65: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  357 |                                                 *(q=findstr(buf,"TO"))=0;
      |                                                                 ^~~~
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o: in function `.L0 ':
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:75: undefined reference to `strtol'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:157: undefined reference to `sprintf'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o:/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:158: undefined reference to `strcat'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o: in function `.L0 ':
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:180: undefined reference to `malloc'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o:/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:186: undefined reference to `atoi'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o: in function `.L0 ':
/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:26: undefined reference to `malloc'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o:/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:242: undefined reference to `sprintf'
/home/icelon/.arduino15/packages/alexandermandera/tools/riscv-none-elf-gcc/12.2.0-3-xPack/bin/../lib/gcc/riscv-none-elf/12.2.0/../../../../riscv-none-elf/bin/ld: /tmp/ccvXmO9o.ltrans0.ltrans.o:/tmp/.arduinoIDE-unsaved2023915-2954-4dhnw1.15zhd/sketch_oct15a/sketch_oct15a.ino:316: undefined reference to `sprintf'
collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by AlexanderMandera** [comment]
`malloc` currently isn't suitable for a MCU with 2KB of RAM, a static size buffer is better in this case.
I would suggest you find alternative implementations for your needed functions.

Implementations for `snprintf` (`mini_snprintf`) etc. are available in the ch32v003fun core.
