### ISSUE TITLE
Board variants

### ISSUE THREAD

**Issue by mcer12** [AlexanderMandera/arduino-wch32v003#7]
First off, apretiate the work you put into this, it has great potential!

There are boards with external oscillator and also without. I guess this project supports the ones with oscillator but are you planning to add board definition for internal HSI oscillator?
For example this one:
https://hackaday.io/project/191287-ch32v003-a4m6-development-board

**Comment by AlexanderMandera** [comment]
Thank you!

With the current state, it only uses the internal oscillator for this.
So this core should also work with any other variant without a problem.

I will add more board options like this inside the Arduino IDE soon.
