### ISSUE TITLE
Error: couldn't open wch link device

### ISSUE THREAD

**Issue by wlkmanist** [AlexanderMandera/arduino-wch32v003#9]
Uploading using MounRiver works fine.

CH32V003F4P6 connected to WCH-LinkE with v2.8 or v2.9 firmware (latest).

![image](https://github.com/AlexanderMandera/arduino-wch32v003/assets/19557325/536cb712-d25e-4959-b55f-13f5010191ff)

**Comment by AlexanderMandera** [comment]
"In Windows, if you want to use minichlink with the LinkE, you will need to use [Zadig](https://zadig.akeo.ie/) to install WinUSB to the WCH-Link interface 0." (ch32v003fun wiki)

This is currently a limitation of minichlink that it doesn't work with the WCH USB drivers. On Linux and Mac, you don't need that. Maybe at some point, this won't be needed but currently it is.

If you want to use WCH software to program again, you can uninstall the WCH LinkE device in device manager and reconnect it. Then it gets the old drivers again.

This is something I have missed to document, which is only documented in ch32v003fun. I will add that to the README soon.

**Comment by PTSolns** [comment]
I'm having the same issue as OP. Tried using the Link-E programmer, as well as others such as Sparkfun Serial Basic board, and others USB-to-UART. Nothing worked. I'm getting same errors as above image shows. Can you please provide more detailed steps as to what needs to be done to resolve this.. The above instructions are not clear. Thanks!

**Comment by AlexanderMandera** [comment]
@PTSolns I have summarized the additional steps required for the Link-E programmer to work with `minichlink`:
https://github.com/AlexanderMandera/arduino-wch32v003/wiki/Additional-Installation-Steps
Let me know if there are any problems with this.

USB-to-UART programmers don't work as V003 use the SWIO protocol for programming.

More programmers (mostly DIY options) can be found here:
https://github.com/cnlohr/ch32v003fun/wiki/Features#minichlink

You can also use an Arduino Uno or similar AVR boards can be used as SWIO programmers as well and should be supported by `minichlink`: https://gitlab.com/BlueSyncLine/arduino-ch32v003-swio

**Comment by PTSolns** [comment]
@AlexanderMandera Thanks for the speedy reply! I did the above steps and now am getting closer. I have a different set of error messages appear in Arduino IDE. The sketch I am trying to run is as follows.

```
uint32_t count;

void setup() {
  pinMode(D0, OUTPUT);
  pinMode(C0, OUTPUT);
}

void loop() {
	digitalWrite(D0, LOW);
	delay(1000);
	digitalWrite(D0, HIGH);
	delay(2000);
  digitalWrite(C0, LOW);
	delay(100);
	digitalWrite(C0, HIGH);
	delay(100);
	count++;
}
```

The resulting error messages are:
![image](https://github.com/AlexanderMandera/arduino-wch32v003/assets/115762362/b0a3521a-af55-4002-8241-a37bd3a87b2d)

Below is my physical hardware connection between the Link-E and the nanoCh32V003 v1.0

Link-E -> nanoCH32V003
U_RX -> D5
U_TX -> D6
GND -> GND
3V3 -> 3V3

Any thoughts? Thanks again.

**Comment by AlexanderMandera** [comment]
You need to connect the SWIO pin of the WCH-LinkE to D1, 3V3 to 3V3 and GND to GND, no UART pins are necessary for flashing

**Comment by PTSolns** [comment]
@AlexanderMandera great I now got it working. Am blinking the onboard LED on D6. Thanks a bunch for the walk-through help.

One thing I am unclear about is why the SWIO pin must be used. Is there no way to use UART pins? I'd like to be able to use other programmers and not the Link-E. For example, I like using the CH340C for UART. Is there a way to get that to work here?

**Comment by AlexanderMandera** [comment]
For the CH32V003 there is no UART bootloader available, that's why the debug interface has to be used.

You could write and flash your own bootloader for that, but that's not trivial and you always need to flash the bootloader the first time using SWIO.

Other programmers like an ESP32-S2 or Arduino Uno-based solution where they implemented the SWIO protocol themselves, are listed in the two links in my previous post.

**Comment by micropythondevel** [comment]
riscv-none-elf-g++: warning: '-x c++' after last input file has no effect
Error: Could not initialize any supported programmers
Error: Could not initialize any supported programmers
Failed uploading: uploading error: exit status 224


help please is linux ....

**Comment by AlexanderMandera** [comment]
Try to follow these instructions:
https://github.com/cnlohr/ch32v003fun/wiki/Installation#non-root-access-on-linux

The udev rules file is also found in the ch32v003fun repository.

I will try to add this to the pre-installation script soon if possible.
